// Writes src/icons/brands.ts: just the simple-icons glyphs the merchant registry uses, so the app bundle doesn't
// carry all ~3,000. Run after adding a brand to src/icons/merchants.ts: `node scripts/brands.mjs`.
import * as si from 'simple-icons'
import { readFileSync, writeFileSync } from 'node:fs'

const reg = readFileSync(new URL('../src/icons/merchants.ts', import.meta.url), 'utf8')
const names = [...new Set([...reg.matchAll(/brand\('(si\w+)'/g)].map((m) => m[1]))].sort()
const rows = names.map((n) => {
  const i = si[n]
  if (!i) throw new Error(`simple-icons has no ${n}`)
  return `  ${n}: { title: ${JSON.stringify(i.title)}, hex: '#${i.hex}', path: ${JSON.stringify(i.path)} },`
})
writeFileSync(new URL('../src/icons/brands.ts', import.meta.url),
  `// Generated by scripts/brands.mjs from simple-icons (CC0). Do not edit by hand.\n` +
  `export interface BrandGlyph { title: string; hex: string; path: string }\n` +
  `export const BRANDS: Record<string, BrandGlyph> = {\n${rows.join('\n')}\n}\n`)
console.log(`${names.length} brand glyphs`)
